In [36]:
import numpy as np
y=[[0.8,0.5,0,-1],[0.9,0.7,0.3,-1],[1,0.8,0.5,-1],[0,0.2,0.3,-1],[0.2,0.1,1.3,-1],[0.2,0.7,0.8,-1]]
d=[1,1,1,-1,-1,-1]
w=[0,0,0,0]
y=np.asarray(y)
d=np.asarray(d)
w=np.array(w)

In [37]:
P=6
p=0
step=0
E=1
c=1
we=[]
e=[]

In [38]:
while(E!=0):
    p=0
    E=0
    for p in range(0,P):
        step=step+1
        #print"Step=",step
        #print"y=",y[p]
        net=np.dot(y[p],w)
        #print"Net=",net
        if(net>0):
            o=1
        elif(net==0):
            o=d[p]*(-1)
        else:
            o=-1
        #print"Output=",o,"d=",d[p]
        if(d[p]!=o):
            w=w+0.5*c*(d[p]-o)*y[p]
            print("yes")
        we.append(w[0])
        print(w,net,o,y[p])
        #print"Weight is ",w
        #print " "
        E=E+0.5*(d[p]-o)*(d[p]-0)
        e.append(E)
    print "Error is ",E
    print("")
    #print " "
print "Final= ",w
print "Steps Required= ",step

yes
(array([ 0.8,  0.5,  0. , -1. ]), 0.0, -1, array([ 0.8,  0.5,  0. , -1. ]))
(array([ 0.8,  0.5,  0. , -1. ]), 2.0700000000000003, 1, array([ 0.9,  0.7,  0.3, -1. ]))
(array([ 0.8,  0.5,  0. , -1. ]), 2.2000000000000002, 1, array([ 1. ,  0.8,  0.5, -1. ]))
yes
(array([ 0.8,  0.3, -0.3,  0. ]), 1.1000000000000001, 1, array([ 0. ,  0.2,  0.3, -1. ]))
(array([ 0.8,  0.3, -0.3,  0. ]), -0.19999999999999998, -1, array([ 0.2,  0.1,  1.3, -1. ]))
yes
(array([ 0.6, -0.4, -1.1,  1. ]), 0.13, 1, array([ 0.2,  0.7,  0.8, -1. ]))
Error is  3.0

yes
(array([ 1.4,  0.1, -1.1,  0. ]), -0.71999999999999986, -1, array([ 0.8,  0.5,  0. , -1. ]))
(array([ 1.4,  0.1, -1.1,  0. ]), 1.0000000000000002, 1, array([ 0.9,  0.7,  0.3, -1. ]))
(array([ 1.4,  0.1, -1.1,  0. ]), 0.93000000000000016, 1, array([ 1. ,  0.8,  0.5, -1. ]))
(array([ 1.4,  0.1, -1.1,  0. ]), -0.31, -1, array([ 0. ,  0.2,  0.3, -1. ]))
(array([ 1.4,  0.1, -1.1,  0. ]), -1.1400000000000001, -1, array([ 0.2,  0.1,  1.3, -1. ]))
(array([ 1

In [35]:
we=np.asarray(we)
we.shape

(24L,)

In [29]:
e=np.asarray(e)
e.shape

(24L,)

In [32]:
import matplotlib.pyplot as plt

In [31]:
plt.plot(we,e)

NameError: name 'plt' is not defined