In [9]:
import numpy as np
import random
import math
m=[[random.randint(-5,5) for i in range(0,3)]for j in range(0,3)]
y=[[10,2,-1],[2,-5,-1],[-5,5,-1]]
d=[[1,-1,-1],[-1,1,-1],[-1,-1,1]]
w=[[1,-2,0],[0,-1,2],[1,3,-1]]
w=np.asarray(w)
y=np.asarray(y)
d=np.asarray(d)
print w

[[ 1 -2  0]
 [ 0 -1  2]
 [ 1  3 -1]]


In [10]:
E=10
net=[0 for i in range(0,3)]
o=[0 for i in range(0,3)]
step=0
cycle=0

In [ ]:
while(E<0.001):
    E=0
    cycle+=1
    for i in range(0,3):
        step+=1
        for j in range(0,3):

In [11]:
while(E>0):
    E=0
    cycle+=1
    for i in range(0,3):
        step+=1
        for j in range(0,3):
            net=np.dot(w[j],y[i])
            if(net<0):
                o[j]=-1
            else:
                o[j]=1
            w[j]=w[j]+0.5*(d[i][j]-o[j])*y[i]
            E=E+0.5*(d[i][j]-o[j])*(d[i][j]-o[j])

In [12]:
print"Cycle",cycle,"Steps=",step
print "Weight matrix="
print w

Cycle 4 Steps= 12
Weight matrix=
[[ 5  3  5]
 [ 0 -1  2]
 [-9  1  0]]
